version: "3.7"
services:
  node:
    ports:
      - "9944:9944"
      - "9933:9933"
      - "30333:30333"
    volumes:
      - node-data:/acala/data
    image: acala/acala-node:latest
    command:
      - "acala"
      - "--base-path=/acala/data"
      - "--chain=mandala"
      - "--node-key=${NODE_ID}"
      - "--port=30333"
      - "--validator"
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      - "--rpc-cors=all"
      - "--force-authoring"
      - "--name=laminar-acala-node"
      - "--ws-max-connections=200"
volumes:
  node-data: